### PR TITLE
Added in Error handling for login

### PR DESCRIPTION
**Pull request by hzyniecki**
- Additional checks are in there as a precaution/future additions, I know they're not needed. 
- Addition of Delete Community API call
- Addition of Watch Party Deletion API call

### CODE REVIEW

**Comment by CarterW715** [comment]
these were moved to their own controller advice class. is that not working for you?

**Comment by hzyniecki** [comment]
Axios wasn't hitting correctly/ I was getting back null data with the old version.

**Comment by CarterW715** [comment]
why did you make the community changes on the (disputed) api error branch?

**Comment by hzyniecki** [comment]
> why did you make the community changes on the (disputed) api error branch?

Accidentally pushed to this branch when I was working off the error changes. I didn't get anymore feedback from you regarding the error changes after I replied so I assumed it was ok.

**Comment by CarterW715** [comment]
:/

**Pull request merged**
